### ISSUE TITLE
Migrating doesn't change definitions in references

### ISSUE THREAD

**Issue by mweber03** [ajv-validator/ajv-cli#112]
The migration changes `definitions` to `$def` at the top, but it does not change the references.

draft-04
```json
{
    "type": "array",
    "items": { "$ref": "#/definitions/positiveInteger" },
    "definitions": {
        "positiveInteger": {
            "type": "integer",
            "exclusiveMinimum": 0
        }
    }
}
```

migration to draft-2019-09
```json
{
    "type": "array",
    "items": { "$ref": "#/definitions/positiveInteger" },  #wrong
    "$defs": {
        "positiveInteger": {
            "type": "integer",
            "exclusiveMinimum": 0
        }
    }
}
```

**Comment by epoberezkin** [comment]
That’s a problem indeed... No idea why I didn’t think about it.

**Comment by epoberezkin** [comment]
Fixing this is not trivial - the problem is not only the complexity of traversing the schema, but deciding which references need to change - they may point to other files.

So if currently files are processed in isolation, they would have to be processed collectively to update the known references only (plus updating definitions may break some other dependencies of these schemas).

The good thing is that it is not necessary - they can just remain definitions - it is still supported in any draft. So the fix is to keep definitions as they are, without changing to $defs.
