### ISSUE TITLE
Consider adding additional formats (from the pajv fork)

### ISSUE THREAD

**Issue by nightwatchcyber** [ajv-validator/ajv-cli#61]
The pajv fork adds supports for other file formats to be verified via JsonSchema. Please consider adding those changes back into this project since the original developer has died.

See:
https://github.com/json-schema-everywhere/pajv
https://github.com/adamvoss

**Comment by epoberezkin** [comment]
PR is welcome

**Comment by G-Rath** [comment]
@epoberezkin 

Am super keen for this as it'll be a major unblocker for integrating all kinds of validation into projects at my work.

I do have a bit of work on my plate right now, so if you've got any particular recommendations or thoughts on how to go about this that'd help narrow the scope of this that'd be a great time saver.

I'm happy to look to pull what pajv has into here, but I believe it's using `any-json`, which was maintained by the same author - from what I know, it should be fine to depend on at least for the short-term, since its pretty feature complete; let me know if you're not ok having that as a dependency, and what alternative you'd recommend using. 

Otherwise, I'll look to pull what pajv has into here, which hopefully be acceptable enough to at least let people iterate on 😄

**Comment by nightwatchcyber** [comment]
Thank you!
